
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team01-m23-10am-3
owner: ucsb-cs156-m23
repo_name: team01-m23-10am-3
pull_requests: [{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Edwin-ZipCode-Controller","number":22,"title":"Add ZipCode Controller and Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/22"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Edwin-ZipCode","number":21,"title":"Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/21"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-University-Controller","number":20,"title":"Add University Controller and Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/20"}]
