
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team01-m23-10am-3
owner: ucsb-cs156-m23
repo_name: team01-m23-10am-3
pull_requests: [{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Edwin-ZipCode-Controller","number":22,"title":"ey - Added ZipCode Controller and Controller Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/22"},{"author":{"id":"U_kgDOBXqlLw","is_bot":false,"login":"Edwin-Yee","name":""},"headRefName":"Edwin-ZipCode","number":21,"title":"Added ZipCode service and tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/21"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-University-Controller","number":20,"title":"Add university controller and tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/20"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"andrewyu6581","name":"andrew"},"headRefName":"Andrew-Tides-Controller","number":19,"title":"Add Tides Controller and Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/19"},{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"Ryan-Location-Controller","number":18,"title":"Add Location Controller and Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/18"},{"author":{"id":"MDQ6VXNlcjg0NTU1NjA5","is_bot":false,"login":"mier2","name":"Xiaoya Zhou"},"headRefName":"Mia-University","number":17,"title":"Add University Service","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/17"},{"author":{"id":"MDQ6VXNlcjU4NDkyMDc2","is_bot":false,"login":"ryan-he-8","name":"Ryan He"},"headRefName":"Ryan-Location","number":16,"title":"Add Location Service","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/16"},{"author":{"id":"MDQ6VXNlcjQ2MzM0NTMz","is_bot":false,"login":"andrewyu6581","name":"andrew"},"headRefName":"Andrew-Tides","number":15,"title":"Add Tides Service and Tests","url":"https://github.com/ucsb-cs156-m23/team01-m23-10am-3/pull/15"}]
